name: qatools
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - netCDF4=1.6.4
  - numpy=1.25.1
  - bokeh=3.2.0
  - holoviews=1.16.2
  - seaborn=0.12.2
  - scipy=1.11.1
  - hvplot=0.8.4
  - pandas=2.0.3
  - pip=23.2
  - pip:
    - nbconvert[webpdf]
    - metpy==1.5.1

